# Generated by Django 4.2.5 on 2024-04-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Inside', models.IntegerField(unique=True)),
                ('Email', models.CharField(max_length=255)),
                ('Corporation', models.CharField(max_length=255)),
                ('Role', models.CharField(max_length=255)),
                ('Subdivision', models.CharField(max_length=255)),
                ('Outside', models.CharField(max_length=255)),
            ],
        ),
    ]
